### ISSUE TITLE
Documentation badge and link are broken

### ISSUE THREAD

**Issue by vringar** [bruxisma/outcome#57]
All other Badges work though.
I'm on mobile, so I can't write a PR right now.

**Comment by bruxisma** [comment]
Ahh, apparently, there's an issue with what I'm seeing on my end and what's rendering with github. Cool. :/

**Comment by bruxisma** [comment]
This is what I get for staying up late to get this release out today. Sorry for the inconvenience!

**Comment by vringar** [comment]
No worries! Thanks for this really interesting crate!
